apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  template:
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"

